# Generated by Django 2.0.6 on 2018-07-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20180715_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_img',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
